program: train.py
name: classify-cifar
method: grid

metric:
  goal: minimize
  name: val_loss

parameters:
  lr:
    min: !!float 1e-5
    max: !!float 1e-3

  batch_size:
    values: [64, 128, 256]

  epochs:
    values: [10, 25, 50, 100, 200]

  conv_blocks:
    values: ["conv2d", "depthwise_conv2d"]

  conv_stack_depth:
    min: 1
    max: 8

  backbone_depth:
    min: 1
    max: 5

  ema_beta:
    min: 0
    max: 1

  ema_update_after_step:
    min: 1
    max: 5000

  ema_update_every:
    min: 1
    max: 100
    
command:
  - ${env}
  - python3
  - ${program}
  - ${args}