program: train.py
name: learning rate sweep
method: grid

metric:
  goal: minimize
  name: val_loss

parameters:
  model:
    values: [mnist]
  learning_rate:
    values: [!!float 1e-3, !!float 4e-4, !!float 2e-4]
  width:
    values: [2, 4, 8]
  depth:
    values: [2, 4, 8]

command:
  - ${env}
  - python3
  - ${program}
  - ${args}
